swagger: '2.0'
info:
  title: POS Print API
  description: Application for cash registers operations
  version: "1.0.0"
host: yourname.telcong.com
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /v1/devices:
    get:
      summary: Retrieve cash registers
      description: Retrieves all cash registers
      tags:
        - Retrieves
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/DeviceRegistrationRequest'
    post:
      summary: Registers device
      parameters:
        - in: body
          name: request
          description: Registers a single cash register device
          required: true
          schema:
            $ref: '#/definitions/DeviceRegistrationRequest'
      tags:
        - Registers
      responses:
        201:
          description: The destination of the registered device
          schema:
            type: object
            items:
              $ref: '#/definitions/DeviceRegistrationResponse'
        400:
          description: Device already exists
          schema:
            $ref: '#/definitions/Error'

  /v1/receipts/req/print:
    post:
      summary: Print Receipts
      parameters:
        - in: body
          name: request
          description: Prining receipts and fiscal receipts
          required: true
          schema:
            $ref: '#/definitions/PrintReceiptRequest'
      description: Prining receipts and fiscal receipts
      responses:
        200:
          description: OK
        400:
          description: Device not found
          schema:
            $ref: "#/definitions/Error"
        480:
          description: Device can't connect
          schema:
            $ref: "#/definitions/Error"

  /v1/reports/operator/print:
    post:
      summary: Prints Report
      parameters:
        - in: body
          name: request
          description: Prints the report for the given operator
          required: true
          schema:
            $ref: '#/definitions/OperatorReportRequest'
      responses:
        200:
          description: Report completed
        400:
          description: Device not found
          schema:
            $ref: "#/definitions/Error"
        480:
          description: Device can't connect
          schema:
            $ref: "#/definitions/Error"

  /v1/reports/periodical/print:
    post:
      summary: Prints Report
      parameters:
        - in: body
          name: request
          description: Prints the report for the given time period
          required: true
          schema:
            $ref: '#/definitions/PeriodReportRequest'
      responses:
        200:
          description: Report completed
        400:
          description: Device not found
          schema:
            $ref: "#/definitions/Error"
        480:
          description: Device can't connect
          schema:
            $ref: "#/definitions/Error"

definitions:
  DeviceRegistrationRequest:
    type: object
    properties:
      sourceIp:
        type: string
        description: Unique ip representing the owner of the device.
        example: '89.100.10.5'
      destination:
        type: string
        description: Unique ip representing the endpoint of the device.
        example: '10.10.5.7'
      description:
        type: string
        description: Description for the device.
        example: 'Cash register one'
  DeviceRegistrationResponse:
    type: object
    properties:
      destination:
        type: string
        description: Unique ip representing the endpoint of the device.
  PrintReceiptRequest:
    type: object
    properties:
      sourceIp:
        type: string
        description: Unique ip representing the owner of the device.
        example: 89.100.10.5
      operatorId:
        type: string
        description: Unique id representing the operator for the device.
        example: "1"
      fiscal:
        type: boolean
        description: true means fiscal receipt, false means text
      receipt:
        type: object
        description: Represents receipt item
        properties:
          receiptId:
            type: string
            description: Receipt ID
            example: "123"
          currency:
            type: string
            description: Currency
            example: "USD"
          prefixLines:
            type: array
            items:
              type: string
          suffixLines:
            type: array
            items:
              type: string
          amount:
            type: number
            format: double
            description: amount to be paid
            example: 1.0
          receiptItems:
            type: object
            description: Represents receipt item
            properties:
              name:
                type: string
                description: Name of the item
                example:
              quantity:
                type: number
                format: double
                description: Quantity of the item
                example: 2.0
              price:
                type: number
                format: double
                description: Price of the item
                example: 1.0
  OperatorReportRequest:
    type: object
    properties:
      sourceIp:
        type: string
        description: Unique ip representing the owner of the device.
        example: 89.100.10.5
      operatorId:
        type: string
        description: Unique id representing the operator for the device.
        example: "1"
      registerState:
        type: string
        description: the state which the chash register is going to acquire
        example: CLEAR or KEEP
  PeriodReportRequest:
    type: object
    properties:
      from:
        type: string
        format: date-time
        description: The starting date for the report
        example: 2017-04-23T18:25:43.511Z
      to:
        type: string
        format: date-time
        description: The ending date for the report
        example: 2017-04-23T18:25:43.511Z
      sourceIp:
        type: string
        description: Unique ip representing the owner of the device.
        example: 89.100.10.5
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
        example: 400
      message:
        type: string
        example: 'Is already present'